[package]
name = "eq_a_by_modules"
version = "0.1.0"
edition = "2021"

[features]
dev-graph=[]

[dependencies]
halo2_proofs = { version="0.3.0", features=["dev-graph"]}
plotters = "0.3.6"
rand_core = "0.6.4"
